version: "3"

services:
  hotel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - "./src:/app/src"
    command:
      - "npm"
      - "run"
      - "start"
